name: Deploying to Pythonanywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Stop Current Running Process
        env:
          PA_API_TOKEN: ${{ secrets.APITOKEN }}
          PA_USERNAME: ${{ secrets.USERNAME }}
          PA_CONSOLE_ID: ${{ secrets.CONSOLE_ID }}
        run: |
          curl -X POST \
            -H "Authorization: Token $PA_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"input": "\u0003"}' \
            https://www.pythonanywhere.com/api/v0/user/$PA_USERNAME/consoles/$PA_CONSOLE_ID/send_input/

      - name: Deploy
        env:
          PA_API_TOKEN: ${{ secrets.APITOKEN }}
          PA_USERNAME: ${{ secrets.USERNAME }}
          PA_CONSOLE_ID: ${{ secrets.CONSOLE_ID }}
        run: |
          curl -X POST \
            -H "Authorization: Token $PA_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"input": "cd quizz_ybot \npip install -r ./src/requirements.txt \npython ./src/main.py \n"}' \
            https://www.pythonanywhere.com/api/v0/user/$PA_USERNAME/consoles/$PA_CONSOLE_ID/send_input/
